SRC = OpenProject.cpp OpenProjectFactory.cpp JsonParser.cpp PreviousDataReader.cpp PreviousDataReaderFactory.cpp DifferAbsorber.cpp

all:
	$(CC) $(INCLUDE) $(OPT) -c $(SRC)

.PHONY: clean
clean:
	$(RM) *.o
