version: "3.7"

services:
  es01:
    image: elasticsearch:8.12.1
    networks:
      - elknet01
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
    environment:
      - network.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    mem_limit: 1GB
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    
  kb01:
    depends_on:
      - es01
    image: kibana:8.12.1
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - 5601:5601
    networks:
      - elknet01
    environment:
      - SERVERNAME=kibana
      - server.host=0.0.0.0
      - elasticsearch.url=http://localhost:9200
      - kibana.index=.kibana
    mem_limit: 1GB

volumes:
  esdata01:
    driver: local
  kibanadata:
    driver: local

networks:
  elknet01:

